Disable buttons during AJAX calls to prevent inconsistent state
systopia/drupal-json_forms pull request #80
Opened 2024-11-08 15:49 UTC by dontub

systopia-reference: 26211

2024-11-12 14:29 UTC, jensschuppe requested changes
Any specific reason for mixing *jQuery* (`.on()`) and vanilla JavaScript (`querySelectorAll()`)?

2024-11-12 14:29 UTC, jensschuppe commented on js/disable-buttons-on-ajax.js
> +      button.setAttribute('disabled', 'true');
This should either use the [native `disabled` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) or [*jQuery*'s `prop()` method](https://api.jquery.com/prop/) instead of altering attributes directly.

2024-11-12 14:29 UTC, jensschuppe commented on js/disable-buttons-on-ajax.js
> +      button.removeAttribute('disabled');
This should either use the [native `disabled` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) or [*jQuery*'s `prop()` method](https://api.jquery.com/prop/) instead of altering attributes directly.

2024-11-13 09:24 UTC, dontub commented on js/disable-buttons-on-ajax.js
> +      button.setAttribute('disabled', 'true');
Changed.

2024-11-13 09:24 UTC, dontub commented on js/disable-buttons-on-ajax.js
> +      button.removeAttribute('disabled');
Changed.

2024-11-13 09:29 UTC, dontub commented
> Any specific reason for mixing _jQuery_ (`.on()`) and vanilla JavaScript (`querySelectorAll()`)?

I initially wanted to use vanilla JavaScript. However with `document.addEventListener('ajaxStart', ...)` the listener wasn't called. I'm not sure, but I guess the reason is that it is an jQuery event. https://api.jquery.com/ajaxStart/

2024-11-13 10:32 UTC, jensschuppe approved these changes

2024-11-13 16:09 UTC, merged